<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.11" />
    <ProjectReference Include="../CodexQuota.Domain/CodexQuota.Domain.csproj" />
    <ProjectReference Include="../CodexQuota.Application/CodexQuota.Application.csproj" />
  </ItemGroup>
</Project>
